/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.BNMO;

import java.util.Scanner;

import com.BNMO.Object.NonFoodObjects.*;
import com.BNMO.Utilities.*;
import com.BNMO.SIMS.Sim;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner userInput = new Scanner(System.in);
        System.out.println("Selamat Datang di Sim-Plicity!");
        System.out.println("Apakah kamu ingin memulai permainan? (Y/N)");
        String startGame = userInput.nextLine();

        while (!startGame.equals("Y") && !startGame.equals("N")) {
            System.out.println("Masukkan Y atau N");
            startGame = userInput.nextLine();
        }

        if (startGame.equals("Y")) {
            Menu menu = new Menu();
            menu.start();
            System.out.println("Masukkan nama sim: ");
            String simName = userInput.nextLine();
            Sim initSim = new Sim(simName);
            World world = new World(initSim);

            menu.viewSimInfo(initSim);
        } else {
            System.out.println("Terima kasih telah bermain!");
        }

    }
}
