/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.BNMO;

import java.util.Scanner;

import com.BNMO.Object.NonFoodObjects.AudioPlayer.AudioPlayer;
import com.BNMO.Object.NonFoodObjects.TV.TV;
import com.BNMO.Object.NonFoodObjects.Toilet.Toilet;
import com.BNMO.Object.NonFoodObjects.Book.Book;
import com.BNMO.Object.NonFoodObjects.Bed.*;

import com.BNMO.Utilities.*;
import com.BNMO.SIMS.Sim;

public class App {

    public static void main(String[] args) {

        Thread timeThread = new Thread(new Runnable() {
            public void run() {
                int i = 1;
                while (true) {
                    try {
                        System.out.println("Hari ke-" + i + " telah dimulai!");
                        System.out.println();
                        Thread.sleep(360000);
                        System.out.println();
                        System.out.println("Telah berlalu setengah hari!");
                        System.out.println();
                        Thread.sleep(300000);
                        System.out.println();
                        System.out.println("Hari ini tersisa 1 menit dalam waktu nyata!");
                        System.out.println();
                        Thread.sleep(60000);
                        System.out.println();
                        System.out.println("Hari telah berganti!");
                        System.out.println();
                        i++;
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });

        timeThread.start();

        Scanner userInput = new Scanner(System.in);
        System.out.println("Selamat Datang di Sim-Plicity!");
        System.out.print("Apakah kamu ingin memulai permainan? (Y/N) ");
        String startGame = userInput.nextLine();
        System.out.println();

        while (!startGame.equals("Y") && !startGame.equals("N")) {
            System.out.println("Masukkan Y atau N!");
            System.out.print("Apakah kamu ingin memulai permainan? (Y/N) ");
            startGame = userInput.nextLine();
            System.out.println();
        }

        if (startGame.equals("Y")) {
            System.out.println("Masukkan nama sim: ");
            String simName = userInput.nextLine();
            Sim initSim = new Sim(simName);
            Menu menu = new Menu(initSim);
            System.out.println();
            menu.start();

            World world = new World(initSim);

            System.out.println();
            menu.viewSimInfo();
            System.out.println();

            while (menu.isGameStarted()) {
                System.out.println("Apa yang ingin kamu lakukan?");
                System.out.println("[1] Help");
                System.out.println("[2] Lihat info sim");
                System.out.println("[3] Lihat info dunia");
                System.out.println("[4] Lihat info rumah");
                System.out.println("[5] Mengganti SIMS");
                System.out.println("[6] Melakukan aktivitas");
                System.out.println("[7] Upgrade rumah");
                System.out.println("[8] Membeli Barang");
                System.out.println("[9] Melihat inventory");
                System.out.println("[10] Exit");
                System.out.println();

                System.out.println("Masukkan perintah: (dalam angka)");
                String command = userInput.nextLine();
                int commandNum;

                try {
                    commandNum = Integer.parseInt(command);
                } catch (NumberFormatException e) {
                    System.out.println("Masukan harus dalam bentuk angka!");
                    command = userInput.nextLine();
                    commandNum = Integer.parseInt(command);
                }

                if (commandNum == 1) {
                    System.out.println();
                    System.out.println("Kamu memanggil help!");
                    menu.help();
                    System.out.println();
                } else if (commandNum == 2) {
                    System.out.println();
                    System.out.println("Berikut adalah info sim kamu:");
                    menu.viewSimInfo();
                    System.out.println();
                } else if (commandNum == 3) {

                }

                else if (commandNum == 4) {

                }

                else if (commandNum == 5) {

                }

                else if (commandNum == 6) {

                }

                else if (commandNum == 7) {

                }

                else if (commandNum == 8) {

                }

                else if (commandNum == 9) {
                    menu.getCurrentSim().getInventory()
                            .addObject(new Book("BukuUwu", 1000, 5, "Meemaw", new Point(0, 0)));
                    menu.getCurrentSim().getInventory()
                            .addObject(new Book("BukuAwa", 1000, 5, "Meemaw", new Point(0, 0)));
                    menu.getCurrentSim().getInventory()
                            .addObject(new Book("BukuIwi", 1000, 5, "Meemaw", new Point(0, 0)));
                    menu.getCurrentSim().getInventory()
                            .addObject(new Book("BukuEwe", 1000, 5, "Meemaw", new Point(0, 0)));
                    menu.getCurrentSim().getInventory().addObject(new SingleBed("myBed", new Point(0, 0)));
                    menu.getCurrentSim().getInventory().addObject(new SingleBed("herBed", new Point(0, 0)));
                    System.out.println();
                    menu.getCurrentSim().getInventory().printInventory();
                    System.out.println();
                }

                else if (commandNum == 10) {
                    menu.exit();
                    break;

                }

                else {
                    System.out.println("Perintah tidak dikenali!");
                    System.out.println();
                }
            }
            userInput.close();

        } else {
            System.out.println("Terima kasih telah bermain!");
        }

    }
}
