/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.BNMO;

import java.util.Scanner;

import com.BNMO.Object.NonFoodObjects.*;
import com.BNMO.Utilities.*;
import com.BNMO.SIMS.Sim;
import com.BNMO.Buildings.House;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner userInput = new Scanner(System.in);
        World world = new World();
        String sim1Name = userInput.nextLine();
        Sim sim1 = new Sim(sim1Name);
        Time worldTime = new Time();

        // TODO : How do we implement time? should we use thread too?

        world.addHouse(new Point(1, 1), sim1);

        System.out.println(world.getHouseList().get(0).getOwner());

        userInput.close();
    }
}
